### ISSUE TITLE
Convert checkpoint: file not found

### ISSUE THREAD

**Issue by coffee4u** [aszc-dev/ComfyUI-CoreMLSuite#39]
When converting a checkpoint, the model will be converted to the .mlpackage file. However, after conversion, the node will check whether there exists a .mlmodelc format file in the 'unet' directory. This results in an error and prevents further progress. I am using the 'convert checkpoint' example workflow
<img width="1234" alt="Screenshot 2024-05-09 at 8 43 49 PM" src="https://github.com/aszc-dev/ComfyUI-CoreMLSuite/assets/674628/d7052048-2552-4707-a9cf-b7a2c87c996a">
<img width="831" alt="Screenshot 2024-05-09 at 8 44 08 PM" src="https://github.com/aszc-dev/ComfyUI-CoreMLSuite/assets/674628/b99c7fe5-a285-4581-8064-4344bacc0f49">

**Comment by ManuelEsteves** [comment]
Hello,

I had the same problem.

In fact, you need to have XCode installed on your Mac. It is apparently necessary to convert ‘mlmodelc’ files.
After installing Xcode, it worked for me

**Comment by coffee4u** [comment]
Thanks @ManuelEsteves ,
I have upgraded my xcode to 15.3 + xcodeselect install...
Still same..

**Comment by ManuelEsteves** [comment]
Hello @coffee4u ,

Personally, I installed the full Xcode (v15.2) from the Apple Store.

You can try changing the path:

To specify the use of Xcode.app (IDE):
**sudo xcode-select --switch /Applications/Xcode.app**

To specify the use of CommandLineTools :
**sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer**

One of the two should work, otherwise, if you don't use XCode very much, I'd advise you to reinstall it from the Apple Store, as this immediately solved the problem

**Comment by coffee4u** [comment]
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
Works for me, thanks @ManuelEsteves !
